unbind C-b
set -g prefix C-n
bind C-n send-prefix

# Terminal / couleurs
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Souris + presse-papier
set -g mouse on
set -g set-clipboard on

# Raccourcis de split
bind h split-window -h
bind v split-window -v

# Touches emacs (utile sous Exegol si EDITOR=vim, tmux passerait en mode vi)
set -g status-keys emacs
set -g mode-keys emacs

# Pour un pentest, un historique plus large est pratique
set -g history-limit 50000
set -s escape-time 10

# --- Thème Tokyo Night : colle ici le contenu du fichier base16 ---
